#!/usr/bin/env node
/**
 * Version single-source (standards.md §5).
 *
 * `VERSION` is NOT exported from ag-grid-community — verified empirically,
 * there is no version export at all. Community's own modules import an
 * internal ./version path that is unreachable from the published package.
 *
 * We therefore derive the version from the INSTALLED package at build time,
 * which removes hand-maintained drift as a possible failure mode.
 *
 * ModuleRegistry compares our module `version` against Community's
 * major.minor. A mismatch logs an error but STILL REGISTERS the module and
 * constructs its beans — so drift fails loudly in the console yet silently
 * in behaviour. Rely on tools/version/check.mjs, not on the warning.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

export function agGridVersion(rootDir = root) {
  const pkgPath = join(rootDir, 'node_modules', 'ag-grid-community', 'package.json');
  if (!existsSync(pkgPath)) {
    throw new Error('ag-grid-community is not installed — run `npm install` first.');
  }
  return JSON.parse(readFileSync(pkgPath, 'utf8')).version;
}

/** Packages that ship a generated src/version.ts — every module-shipping package. */
export const VERSIONED_PACKAGES = [
  'core',
  'menu',
  'side-bar',
  'material',
  'row-grouping',
  'columns-tool-panel',
  'cell-selection',
  'clipboard',
  'status-bar',
  'toolbar',
  'excel-export',
  'set-filter',
  'multi-filter',
  'filters-tool-panel',
  'server-side-row-model',
  'pivot',
  'viewport-row-model',
  'tree-data',
  'master-detail',
  'advanced-filter',
  'find',
  'rich-select',
  'integrated-charts',
  'sparklines',
  'batch-edit',
  'calculated-columns',
];

export function generate(rootDir = root) {
  const version = agGridVersion(rootDir);
  const written = [];
  for (const pkg of VERSIONED_PACKAGES) {
    const dir = join(rootDir, 'packages', pkg, 'src');
    mkdirSync(dir, { recursive: true });
    const file = join(dir, 'version.ts');
    writeFileSync(
      file,
      `// GENERATED by tools/version/generate.mjs — do not edit.\n` +
        `// Sourced from the installed ag-grid-community package.\n` +
        `export const VERSION = '${version}';\n`,
    );
    written.push(`packages/${pkg}/src/version.ts`);
  }
  return { version, written };
}

if (process.argv[1] && process.argv[1].endsWith('generate.mjs')) {
  const { version, written } = generate();
  console.log(`✅ VERSION = ${version}`);
  for (const w of written) console.log(`   wrote ${w}`);
}
