#!/usr/bin/env node
/**
 * LibreGrid lockstep version: manifest sync + docs version generation.
 *
 * The project version IS the lockstep package version, canonical at
 * packages/core/package.json (docs/design/release-versioning-plan.md).
 *
 *   node tools/version/workspace.mjs sync      # bump root + docs manifests
 *   node tools/version/workspace.mjs generate  # write apps/docs/src/version.ts
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

/** Private manifests that must mirror the lockstep version. */
export const SYNCED_MANIFESTS = ['package.json', 'apps/docs/package.json'];

export const DOCS_VERSION_FILE = 'apps/docs/src/version.ts';

export function libregridVersion(rootDir = root) {
  const pkg = JSON.parse(readFileSync(join(rootDir, 'packages/core/package.json'), 'utf8'));
  return pkg.version;
}

/**
 * changesets/action treats every package whose version field changed during
 * the version command as released and reads its CHANGELOG.md for the version
 * PR body. The synced private manifests therefore each need a changelog entry.
 */
function ensureChangelogEntry(rootDir, manifestRel, version) {
  const manifestDir = dirname(join(rootDir, manifestRel));
  const changelogPath = join(manifestDir, 'CHANGELOG.md');
  const name = JSON.parse(readFileSync(join(rootDir, manifestRel), 'utf8')).name;
  const entry = `## ${version}\n\nVersion synced with the lockstep release.`;
  if (!existsSync(changelogPath)) {
    writeFileSync(changelogPath, `# ${name}\n\n${entry}\n`);
    return true;
  }
  const contents = readFileSync(changelogPath, 'utf8');
  if (contents.includes(`## ${version}`)) return false;
  const lines = contents.split('\n');
  const titleIndex = lines.findIndex((line) => line.startsWith('# '));
  lines.splice(titleIndex + 1, 0, '', entry);
  writeFileSync(changelogPath, lines.join('\n'));
  return true;
}

/** Writes the lockstep version into the private workspace manifests. */
export function syncManifests(rootDir = root) {
  const version = libregridVersion(rootDir);
  const written = [];
  for (const rel of SYNCED_MANIFESTS) {
    const path = join(rootDir, rel);
    const contents = readFileSync(path, 'utf8');
    // Replace only the version field so formatting elsewhere is preserved.
    const updated = contents.replace(/"version": "[^"]*"/, `"version": "${version}"`);
    if (updated !== contents) {
      writeFileSync(path, updated);
      written.push(rel);
    }
    if (ensureChangelogEntry(rootDir, rel, version)) {
      written.push(join(dirname(rel), 'CHANGELOG.md'));
    }
  }
  return { version, written };
}

/** Emits the version the docs app renders — never hand-edit the badge. */
export function generateDocsVersion(rootDir = root) {
  const version = libregridVersion(rootDir);
  writeFileSync(
    join(rootDir, DOCS_VERSION_FILE),
    `// GENERATED by tools/version/workspace.mjs — do not edit.\n` +
      `// Sourced from packages/core/package.json (the lockstep project version).\n` +
      `export const LIBREGRID_VERSION = '${version}';\n`,
  );
  return version;
}

if (process.argv[1] && process.argv[1].endsWith('workspace.mjs')) {
  const command = process.argv[2];
  if (command === 'sync') {
    const { version, written } = syncManifests();
    console.log(`✅ Synced manifests to ${version}`);
    for (const w of written) console.log(`   wrote ${w}`);
  } else if (command === 'generate') {
    const version = generateDocsVersion();
    console.log(`✅ LIBREGRID_VERSION = ${version}`);
    console.log(`   wrote ${DOCS_VERSION_FILE}`);
  } else {
    console.error('Usage: node tools/version/workspace.mjs [sync|generate]');
    process.exit(1);
  }
}
