import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { DocsBackendBoundaryComponent, type DocsBoundaryContract, type DocsBoundaryResponsibility } from './docs-backend-boundary';
import { DocsCodeExampleComponent, type DocsCodeExample } from './docs-code-example';
import { DocsProductionChecklistComponent, type DocsChecklistItem } from './docs-production-checklist';
import type { DocsFeature } from './feature-catalog';

export interface DocsRouteGuide {
  readonly intro: string;
  readonly steps: readonly { title: string; instruction: string; expected: string; icon: string }[];
  readonly checklist?: readonly DocsChecklistItem[];
  readonly clientResponsibilities?: readonly DocsBoundaryResponsibility[];
  readonly backendResponsibilities?: readonly DocsBoundaryResponsibility[];
  readonly contracts?: readonly DocsBoundaryContract[];
}

const REQUIRED: readonly DocsChecklistItem[] = [
  { title: 'Register the module once', description: 'Keep module registration in the application composition root before any grid mounts.', priority: 'required' },
  { title: 'Use stable row identity', description: 'Provide getRowId whenever users can edit, select, expand, or persist grid state.', priority: 'recommended' },
  { title: 'Test the customer task', description: 'Automate the successful flow a user sees in this live guide, including keyboard operation.', priority: 'recommended' },
];

const DATA_REQUIRED: readonly DocsChecklistItem[] = [
  { title: 'Authorize every request', description: 'Treat filters, routes, and row IDs as user input; enforce tenant and policy constraints in your systems.', priority: 'required' },
  { title: 'Bound the query or stream', description: 'Validate ranges, debounce churn, and expose only indexed or supported fields.', priority: 'required' },
  { title: 'Observe real latency', description: 'Record request shape, duration, errors, and empty results before expanding rollout.', priority: 'recommended' },
];

/**
 * Task-oriented documentation for legacy demo routes. The component frame
 * turns every existing demo into the same product → try → integrate → ship
 * journey used by the rebuilt flagship pages without replacing their working
 * grid behavior.
 */
export const ROUTE_GUIDES: Readonly<Record<string, DocsRouteGuide>> = {
  grid: { intro: 'Start here to see the base Community grid that LibreGrid extends.', steps: [{ title: 'Scan a real row', instruction: 'Sort a useful column and resize it to match the work at hand.', expected: 'The grid keeps information legible without a custom table.', icon: 'table_chart' }, { title: 'Choose the next capability', instruction: 'Use the navigation to add grouping, filters, or editing only when a customer needs it.', expected: 'The package boundary remains deliberate.', icon: 'extension' }] },
  menus: { intro: 'Menus turn familiar grid affordances into an extensible workspace.', steps: [{ title: 'Open a context menu', instruction: 'Right-click a cell or use the keyboard trigger.', expected: 'Actions are scoped to the row and cell the user chose.', icon: 'menu' }, { title: 'Inspect a column action', instruction: 'Open a header menu and follow a submenu.', expected: 'Feature packages can contribute actions without owning the menu shell.', icon: 'account_tree' }] },
  'side-bar': { intro: 'Side panels keep configuration near the data without overwhelming the main workspace.', steps: [{ title: 'Open a panel', instruction: 'Open Columns or Filters, then return to the data.', expected: 'The grid remains visible while the workspace changes.', icon: 'vertical_split' }, { title: 'Change position', instruction: 'Move the panel between left and right.', expected: 'The renderer preserves a usable, accessible tab relationship.', icon: 'swap_horiz' }] },
  toolbar: { intro: 'Use the toolbar as the compact command surface for a data-heavy workflow.', steps: [{ title: 'Narrow the dataset', instruction: 'Type into the quick filter.', expected: 'Visible rows change immediately and the workspace retains context.', icon: 'filter_alt' }, { title: 'Configure analysis', instruction: 'Use the embedded zones to add a row group or pivot.', expected: 'The toolbar handles intent while the grid renders the result.', icon: 'tune' }] },
  'row-grouping': { intro: 'Grouping helps operations teams move from individual records to meaningful totals.', steps: [{ title: 'Expand a summary', instruction: 'Open a grouped row.', expected: 'The total and the contributing records stay connected.', icon: 'unfold_more' }, { title: 'Compare outcomes', instruction: 'Sort or change an aggregation.', expected: 'Users can answer “where is the volume?” without exporting first.', icon: 'analytics' }] },
  pivot: { intro: 'Pivoting converts operational records into a cross-tab report in the same workspace.', steps: [{ title: 'Enable pivot mode', instruction: 'Toggle the pivot view.', expected: 'Generated column groups make the comparison explicit.', icon: 'pivot_table_chart' }, { title: 'Adjust dimensions', instruction: 'Use the Columns panel to change a pivot or value field.', expected: 'The report updates from the source rows.', icon: 'view_column' }] },
  columns: { intro: 'Column tools let each user make the grid fit their work without a custom report builder.', steps: [{ title: 'Open the chooser', instruction: 'Hide or show a useful field.', expected: 'The table becomes less noisy while row data stays intact.', icon: 'visibility' }, { title: 'Build an analysis', instruction: 'Add a row group or aggregation in the panel.', expected: 'The user’s workspace becomes an interactive report.', icon: 'view_column' }] },
  filters: { intro: 'Filters narrow large datasets with an explicit, inspectable set of conditions.', steps: [{ title: 'Add a filter', instruction: 'Choose a field from the filter panel.', expected: 'A visible card describes exactly why rows are included.', icon: 'add_circle' }, { title: 'Combine conditions', instruction: 'Apply another filter or switch filter type.', expected: 'Users can refine results without losing their first condition.', icon: 'filter_alt' }] },
  selection: { intro: 'Cell selection and clipboard make a grid feel like an operational spreadsheet without leaving the application.', steps: [{ title: 'Select a range', instruction: 'Drag across related cells.', expected: 'The selected range stays visually clear.', icon: 'select_all' }, { title: 'Copy or fill', instruction: 'Copy the range or drag the fill handle.', expected: 'Users can move structured values with predictable results.', icon: 'content_copy' }] },
  'excel-export': { intro: 'Export gives customers a governed hand-off when analysis must leave the application.', steps: [{ title: 'Export the current work', instruction: 'Use the single-sheet export action.', expected: 'A workbook reflects the visible grid data.', icon: 'download' }, { title: 'Build a workbook', instruction: 'Use the multiple-sheet action.', expected: 'Related views arrive together without manual copy-and-paste.', icon: 'table_view' }] },
  'server-side': { intro: 'SSRM makes a large dataset feel responsive by asking your service only for visible blocks.', steps: [{ title: 'Move through pages', instruction: 'Use the pager to jump across the dataset.', expected: 'Only the requested range is loaded.', icon: 'skip_next' }, { title: 'Sort a server field', instruction: 'Sort a column.', expected: 'The next request carries the sort model to your data system.', icon: 'sort' }], checklist: DATA_REQUIRED, clientResponsibilities: [{ title: 'Request visible blocks', description: 'Send range and sort intent through the datasource.' }], backendResponsibilities: [{ title: 'Query and page', description: 'Return the requested rows and an accurate total count.' }], contracts: [{ kind: 'Request', name: 'IServerSideGetRowsRequest', description: 'Range, sort, filter, group, and pivot intent.' }, { kind: 'Response', name: '{ rowData, rowCount }', description: 'A block of rows plus a total.' }] },
  'server-side-selection': { intro: 'Durable selection stores intent in your systems, not in the browser’s loaded row cache.', steps: [{ title: 'Filter the dataset', instruction: 'Filter by a desk before selecting.', expected: 'Selection captures the current filter scope.', icon: 'filter_alt' }, { title: 'Select across pages', instruction: 'Use Select All in the selection footer.', expected: 'The compact specification represents rows that are not loaded.', icon: 'playlist_add_check' }], checklist: DATA_REQUIRED, clientResponsibilities: [{ title: 'Send compact operations', description: 'Write select/deselect operations and resolve loaded row flags.' }], backendResponsibilities: [{ title: 'Persist selection specs', description: 'Apply terms and exceptions atomically per user and workspace.' }], contracts: [{ kind: 'Provider', name: 'ServerSideSelectionProvider', description: 'getSpec, applyOps, and resolveSelected form the application seam.' }] },
  viewport: { intro: 'Viewport rows are for live feeds where the server pushes what the current window should show.', steps: [{ title: 'Scroll the live window', instruction: 'Move through the viewport.', expected: 'The view requests a new range rather than creating every row locally.', icon: 'visibility' }, { title: 'Watch updates arrive', instruction: 'Leave the grid active as the feed changes.', expected: 'Row updates are pushed into the existing viewport.', icon: 'sync' }], checklist: DATA_REQUIRED, clientResponsibilities: [{ title: 'Report viewport range', description: 'Tell the feed which indexes are currently visible.' }], backendResponsibilities: [{ title: 'Push only active rows', description: 'Publish updates for the subscribed range with stable identity.' }], contracts: [{ kind: 'Stream', name: 'setRowData / setRowCount', description: 'Push total count and changed rows into the viewport model.' }] },
  'tree-data': { intro: 'Tree Data expresses ownership and hierarchy while keeping every node as ordinary row data.', steps: [{ title: 'Navigate a branch', instruction: 'Expand and collapse a parent.', expected: 'Users see where a record belongs without a separate drill-down.', icon: 'account_tree' }, { title: 'Move a record', instruction: 'Use the supported reparenting interaction.', expected: 'The path and visible hierarchy stay in sync.', icon: 'drive_file_move' }] },
  'calculated-columns': { intro: 'Calculated columns let users see derived business measures without copying data into another tool.', steps: [{ title: 'Inspect a formula', instruction: 'Read Profit and Unit Price in the grid.', expected: 'Derived values are clearly read-only.', icon: 'functions' }, { title: 'Create a calculation', instruction: 'Open a header menu and add a calculated column.', expected: 'Validation feedback prevents an invalid value from masquerading as data.', icon: 'calculate' }] },
  'ai-toolkit': { intro: 'The AI Toolkit turns plain-language requests into validated grid-state changes, inferred by a small model running entirely in the browser.', steps: [{ title: 'Ask for a change', instruction: 'Type a request or pick a suggestion chip.', expected: 'The local model picks one of four flat tools and scores its confidence.', icon: 'auto_awesome' }, { title: 'Watch it apply', instruction: 'Read the log line under the grid.', expected: 'Applied calls show the provider and confidence; low-confidence requests ask for clarification instead of guessing.', icon: 'verified' }] },
  'advanced-filter-find': { intro: 'Advanced Filter and Find turn a large grid into a searchable decision surface.', steps: [{ title: 'Build an expression', instruction: 'Open the advanced builder and combine conditions.', expected: 'The serializable expression visibly controls the rows.', icon: 'filter_alt' }, { title: 'Find a rendered value', instruction: 'Enter a term and advance to the next match.', expected: 'Find highlights and navigates matches without changing the filter.', icon: 'manage_search' }] },
  'batch-edit': { intro: 'Batch editing gives teams a reviewable change set instead of accidental one-cell-at-a-time writes.', steps: [{ title: 'Stage changes', instruction: 'Start a batch and edit several values.', expected: 'Pending changes remain visible before they are committed.', icon: 'edit_note' }, { title: 'Choose the outcome', instruction: 'Commit or cancel the batch.', expected: 'The entire set is applied or discarded predictably.', icon: 'rule' }] },
  'row-numbers': { intro: 'Row numbers provide an unambiguous reference for dense, frequently discussed records.', steps: [{ title: 'Reference a row', instruction: 'Read the row-number column or select a row from it.', expected: 'Teams can point to the same record quickly.', icon: 'format_list_numbered' }, { title: 'Adjust density', instruction: 'Enable the row resizer and change a row height.', expected: 'The reference column stays aligned with the data.', icon: 'height' }] },
  'column-header-edit': { intro: 'Editable headers let users speak their business language without a separate configuration screen.', steps: [{ title: 'Rename a field', instruction: 'Open header editing for an eligible column.', expected: 'The header changes live and is represented in column state.', icon: 'edit' }, { title: 'Choose apply mode', instruction: 'Switch between immediate and deferred apply.', expected: 'Teams can control whether an edit is committed as they work.', icon: 'published_with_changes' }] },
  notes: { intro: 'Cell Notes make context visible directly where a customer needs to act.', steps: [{ title: 'Open a note', instruction: 'Hover or click a noted cell.', expected: 'The operational context appears without navigating away.', icon: 'sticky_note_2' }, { title: 'Add or clear context', instruction: 'Create a note, then clear it from the demo.', expected: 'Markers and popups stay synchronized with stored note data.', icon: 'note_add' }] },
  angular: { intro: 'Angular helpers make grid state composable with the rest of a signal-based application.', steps: [{ title: 'Change grid state', instruction: 'Filter by a name.', expected: 'The state chips update from Grid API signals.', icon: 'filter_alt' }, { title: 'Inspect typed configuration', instruction: 'Use the copyable setup below the demo.', expected: 'Application code stays explicit about modules and options.', icon: 'code' }] },
  sparklines: { intro: 'Sparklines surface directional change inside the operational rows users already scan.', steps: [{ title: 'Compare accounts', instruction: 'Read usage and retention shapes across rows.', expected: 'A trend is visible without opening a separate chart.', icon: 'show_chart' }, { title: 'Connect your series', instruction: 'Review the backend note after the grid.', expected: 'Your API remains responsible for ordered numeric series.', icon: 'storage' }] },
};

const MODULE_EXPORTS: Readonly<Record<string, readonly string[]>> = {
  '@libregrid/menu': ['ContextMenuModule', 'ColumnMenuModule'], '@libregrid/side-bar': ['SideBarModule'], '@libregrid/toolbar': ['ToolbarModule'], '@libregrid/row-grouping': ['RowGroupingModule'], '@libregrid/pivot': ['PivotModule'], '@libregrid/columns-tool-panel': ['ColumnsToolPanelModule', 'RowGroupingPanelModule'], '@libregrid/cell-selection': ['CellSelectionModule'], '@libregrid/clipboard': ['ClipboardModule'], '@libregrid/status-bar': ['StatusBarModule'], '@libregrid/excel-export': ['ExcelExportModule'], '@libregrid/server-side-row-model': ['ServerSideRowModelModule'], '@libregrid/server-side-selection': ['ServerSideSelectionModule'], '@libregrid/viewport-row-model': ['ViewportRowModelModule'], '@libregrid/tree-data': ['TreeDataModule'], '@libregrid/calculated-columns': ['CalculatedColumnsModule'], '@libregrid/advanced-filter': ['AdvancedFilterModule'], '@libregrid/find': ['FindModule'], '@libregrid/rich-select': ['RichSelectModule'], '@libregrid/batch-edit': ['BatchEditModule'], '@libregrid/row-numbers': ['RowNumbersModule'], '@libregrid/column-header-edit': ['ColumnHeaderEditModule'], '@libregrid/notes': ['NotesModule'], '@libregrid/sparklines': ['SparklinesModule'], '@libregrid/integrated-charts': ['IntegratedChartsModule'], '@libregrid/ai-toolkit': ['AiToolkitModule'],
};

function setupExamples(feature: DocsFeature): readonly DocsCodeExample[] {
  if (feature.path === 'grid') {
    return [{ id: 'grid', label: 'Angular grid', language: 'TypeScript', filename: 'main.ts', description: 'Start with Community. The same provider becomes the single registration point when a LibreGrid capability is added.', code: `import { provideLibreGrid } from '@libregrid/angular';\nimport { AllCommunityModule } from 'ag-grid-community';\n\nbootstrapApplication(AppComponent, {\n  providers: [provideLibreGrid(AllCommunityModule)],\n});\n\n// Then render <ag-grid-angular [rowData]="orders" [columnDefs]="columns" />\n// in the feature component.` }];
  }
  if (feature.path === 'angular') {
    return [{ id: 'angular', label: 'Angular registration', language: 'TypeScript', filename: 'main.ts', description: 'The Angular adapter registers exactly the chosen grid modules once and exposes typed helpers in route components.', code: `import { provideLibreGrid } from '@libregrid/angular';\nimport { RowGroupingModule } from '@libregrid/row-grouping';\n\nbootstrapApplication(AppComponent, {\n  providers: [provideLibreGrid(RowGroupingModule)],\n});` }];
  }
  const imports = feature.packages.filter((packageName) => MODULE_EXPORTS[packageName]).map((packageName) => ({ packageName, modules: MODULE_EXPORTS[packageName]! }));
  const importLines = imports.map(({ packageName, modules }) => `import { ${modules.join(', ')} } from '${packageName}';`).join('\n');
  const modules = imports.flatMap((entry) => entry.modules);
  const registration = modules.length ? `provideLibreGrid(${modules.join(', ')})` : 'provideLibreGrid()';
  const examples: DocsCodeExample[] = [{ id: 'angular', label: 'Angular registration', language: 'TypeScript', filename: 'main.ts', description: 'Register this capability once at the application composition root; route components should not self-register modules.', code: `npm install ${feature.packages.join(' ')}\n\nimport { provideLibreGrid } from '@libregrid/angular';\n${importLines}\n\nbootstrapApplication(AppComponent, {\n  providers: [${registration}],\n});` }];
  if (feature.path === 'server-side') examples.push({ id: 'backend', label: 'Backend query', language: 'TypeScript', filename: 'orders.controller.ts', description: 'The datasource sends range, sort, and filter intent; the backend controls authorization and query planning.', code: `app.post('/api/orders/query', async (request, response) => {\n  const query = request.body as IServerSideGetRowsRequest;\n  const result = await orders.query({\n    start: query.startRow, end: query.endRow,\n    sort: query.sortModel, filter: query.filterModel,\n  });\n  response.json({ rowData: result.rows, rowCount: result.total });\n});` });
  if (feature.path === 'server-side-selection') examples.push({ id: 'backend', label: 'Selection provider', language: 'TypeScript', filename: 'selection-provider.ts', description: 'Persist compact terms and exceptions in your systems; resolve the current block of row IDs on demand.', code: `const provider: ServerSideSelectionProvider = {\n  getSpec: ({ gridId, tabId }) => selectionStore.get(gridId, tabId),\n  applyOps: ({ gridId, tabId, ops }) => selectionStore.apply(gridId, tabId, ops),\n  resolveSelected: ({ gridId, tabId, rowIds, groupRoutes }) =>\n    selectionStore.resolve(gridId, tabId, rowIds, groupRoutes),\n};` });
  if (feature.path === 'viewport') examples.push({ id: 'backend', label: 'Live feed', language: 'TypeScript', filename: 'quote-feed.service.ts', description: 'Subscribe the visible range and push only changed rows into that viewport.', code: `socket.on('viewport', ({ firstRow, lastRow }) => {\n  quoteFeed.subscribe({ firstRow, lastRow, onUpdate: (row) => {\n    gridApi.setRowData({ rowIndex: row.index, rowData: row });\n  }});\n});` });
  if (feature.boundary === 'Both' && !['server-side', 'server-side-selection', 'viewport'].includes(feature.path)) examples.push({ id: 'persistence', label: 'Persist workspace state', language: 'TypeScript', filename: 'workspace-preferences.service.ts', description: 'Use your existing preferences or collaboration service for saved filters, column labels, notes, and other user-owned state.', code: `await preferences.save({\n  userId: session.userId,\n  gridId: 'orders',\n  columnState: gridApi.getColumnState(),\n  filterModel: gridApi.getFilterModel(),\n});\n\nconst saved = await preferences.load(session.userId, 'orders');\ngridApi.applyColumnState({ state: saved.columnState });\ngridApi.setFilterModel(saved.filterModel);` });
  return examples;
}

/** The consistent integration and production portion appended to every legacy demo route. */
@Component({
  selector: 'lgr-docs-route-companion',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DocsBackendBoundaryComponent, DocsCodeExampleComponent, DocsProductionChecklistComponent],
  styles: `:host { display:block; max-width:1280px; margin:0 auto; padding:0 clamp(1.5rem, 3vw, 2.5rem) 2rem; }`,
  template: `
    <lgr-docs-code-example heading="Add this capability to your application" [examples]="examples()" />
    @if (guide().clientResponsibilities && guide().backendResponsibilities) {
      <lgr-docs-backend-boundary [summary]="backendSummary()" [clientResponsibilities]="guide().clientResponsibilities!" [backendResponsibilities]="guide().backendResponsibilities!" [contracts]="guide().contracts ?? []" />
    }
    <lgr-docs-production-checklist [items]="guide().checklist ?? defaultChecklist" />
  `,
})
export class DocsRouteCompanionComponent {
  readonly feature = input.required<DocsFeature>();
  readonly guide = input.required<DocsRouteGuide>();
  protected readonly examples = computed(() => setupExamples(this.feature()));
  protected readonly defaultChecklist = REQUIRED;
  protected backendSummary(): string { return `${this.feature().label} keeps the grid interaction in the browser; your application remains responsible for data access, policy, persistence, and observability.`; }
}
