import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { MatToolbarModule } from '@angular/material/toolbar';

/** Angular Material presentation shell for live status-panel output. @feature Status Bar */
@Component({
  selector: 'lgr-material-status-bar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MatToolbarModule],
  template:
    '<mat-toolbar class="lgr-status-bar" role="status" aria-live="polite">{{ text }}</mat-toolbar>',
})
export class MaterialStatusBarComponent {
  /** Human-readable current status generated by configured status panels. */
  @Input({ required: true }) public text = '';
}
