import { Component, ChangeDetectionStrategy, inject, signal } from '@angular/core';
import { AgGridAngular } from 'ag-grid-angular';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { type ColDef, type GridOptions, type GridApi } from 'ag-grid-community';

import { LibreGridThemeService } from '@libregrid/material';

interface Row {
  name: string;
  region: string;
  sales: number;
}

const NAMES = ['Alice', 'Bruno', 'Carmen', 'Dmitri', 'Elena', 'Farid', 'Grace', 'Hiro', 'Ines', 'Jonas'] as const;
const REGIONS = ['North', 'South', 'East', 'West'] as const;

function makeRows(n: number): Row[] {
  const rows: Row[] = [];
  for (let i = 0; i < n; i++) {
    rows.push({
      name: NAMES[i % NAMES.length]!,
      region: REGIONS[i % REGIONS.length]!,
      sales: Math.round(((i * 7919) % 10000) + 100),
    });
  }
  return rows;
}

@Component({
  selector: 'lgr-row-numbers-demo',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AgGridAngular, MatCardModule, MatButtonModule],
  template: `
    <div class="lgr-page">
      <h1>Row Numbers</h1>
      <p>
        <code>rowNumbers</code> adds a row-number column at the start of the grid.
        Each cell is the 1-based visible row index. With <code>cellSelection</code>
        enabled, clicking a row number selects the whole visible row;
        <code>rowNumbers.enableRowResizer</code> adds a drag handle on each
        row-number cell's bottom edge.
      </p>

      <mat-card appearance="outlined">
        <mat-card-content>
          <div class="lgr-grid-host">
            <ag-grid-angular
              style="width: 100%; height: 420px;"
              [theme]="theme.gridTheme()"
              [columnDefs]="columnDefs"
              [rowData]="rowData()"
              [gridOptions]="gridOptions"
              (gridReady)="onGridReady($event.api)"
              data-testid="row-numbers-grid"
            />
          </div>
        </mat-card-content>
      </mat-card>

      <h2>Options</h2>
      <div class="lgr-actions">
        <button mat-stroked-button [class.lgr-active]="rowNumbers()" (click)="toggleRowNumbers()">
          {{ rowNumbers() ? 'rowNumbers: on' : 'rowNumbers: off' }}
        </button>
        <button mat-stroked-button [class.lgr-active]="enableRowResizer()" (click)="toggleRowResizer()">
          {{ enableRowResizer() ? 'Row resizer: on' : 'Row resizer: off' }}
        </button>
        <button mat-stroked-button [class.lgr-active]="cellSelection()" (click)="toggleCellSelection()">
          {{ cellSelection() ? 'Cell selection: on' : 'Cell selection: off' }}
        </button>
      </div>

      <h2>How it works</h2>
      <p>
        Register <code>RowNumbersModule</code> and set <code>rowNumbers: true</code>
        (or an options object). The column is generated by the reserved
        <code>rowNumbersSvc</code> bean: locked left (right in RTL), not sortable
        or movable, 60px wide by default, and excluded from charts and exports
        unless <code>exportRowNumbers: true</code>.
      </p>
    </div>
  `,
})
export class RowNumbersDemo {
  protected readonly theme = inject(LibreGridThemeService);
  protected readonly rowData = signal<Row[]>(makeRows(20));
  protected readonly rowNumbers = signal(true);
  protected readonly enableRowResizer = signal(true);
  protected readonly cellSelection = signal(true);
  private api: GridApi | undefined;

  protected readonly columnDefs: ColDef<Row>[] = [
    { field: 'name', minWidth: 140 },
    { field: 'region', minWidth: 110 },
    { field: 'sales', type: 'numericColumn', minWidth: 110 },
  ];

  protected readonly gridOptions: GridOptions<Row> = {
    rowNumbers: { enableRowResizer: true },
    cellSelection: true,
  } as never;

  onGridReady(gridApi: GridApi): void {
    this.api = gridApi;
  }

  protected toggleRowNumbers(): void {
    this.rowNumbers.update((on) => !on);
    this.api?.setGridOption('rowNumbers', this.rowNumbers() ? { enableRowResizer: this.enableRowResizer() } : false);
  }

  protected toggleRowResizer(): void {
    this.enableRowResizer.update((on) => !on);
    this.api?.setGridOption('rowNumbers', {
      enableRowResizer: this.enableRowResizer(),
    });
  }

  protected toggleCellSelection(): void {
    this.cellSelection.update((on) => !on);
    this.api?.setGridOption('cellSelection', this.cellSelection());
  }
}
