import { Component, ChangeDetectionStrategy, inject } from '@angular/core';
import { AgGridAngular } from 'ag-grid-angular';
import { MatCardModule } from '@angular/material/card';
import type { ColDef, GridOptions } from 'ag-grid-community';

import { LibreGridThemeService } from '@libregrid/material';

interface Row {
  country: string;
  city: string;
  product: string;
  sales: number;
}

const COUNTRIES = ['United States', 'France', 'Japan', 'Brazil', 'Germany'] as const;
const CITIES: Record<string, string[]> = {
  'United States': ['New York', 'Los Angeles', 'Chicago'],
  France: ['Paris', 'Lyon', 'Marseille'],
  Japan: ['Tokyo', 'Osaka', 'Kyoto'],
  Brazil: ['São Paulo', 'Rio de Janeiro', 'Brasília'],
  Germany: ['Berlin', 'Munich', 'Hamburg'],
};
const PRODUCTS = ['Widget', 'Gadget', 'Doohickey'] as const;

function makeRows(n: number): Row[] {
  const rows: Row[] = [];
  for (let i = 0; i < n; i++) {
    const country = COUNTRIES[i % COUNTRIES.length]!;
    const cityPool = CITIES[country]!;
    rows.push({
      country,
      city: cityPool[i % cityPool.length]!,
      product: PRODUCTS[i % PRODUCTS.length]!,
      sales: Math.round(((i * 7919) % 10000) + 100),
    });
  }
  return rows;
}

@Component({
  selector: 'lgr-row-grouping',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AgGridAngular, MatCardModule],
  template: `
    <div class="lgr-page">
      <h1>Row Grouping</h1>
      <p>
        Data is grouped by <strong>country</strong>
        (and <strong>city</strong> when expanded) via
        <code>rowGroup: true</code> on the column definition.
      </p>

      <mat-card appearance="outlined">
        <mat-card-content>
          <div class="lgr-grid-host">
            <ag-grid-angular
              style="width: 100%; height: 500px;"
              [theme]="theme.gridTheme()"
              [columnDefs]="columnDefs"
              [rowData]="rowData"
              [gridOptions]="gridOptions"
              data-testid="row-grouping-grid"
            />
          </div>
        </mat-card-content>
      </mat-card>

      <h2>How it works</h2>
      <p>
        The <code>&#64;libregrid/row-grouping</code> package registers a
        <code>GroupStage</code> and <code>FlattenStage</code> bean that
        Community's Client-Side Row Model calls automatically when a column has
        <code>rowGroup: true</code>.
      </p>
      <p>
        Aggregation is provided by <code>AggFuncService</code> (built-ins
        <code>sum</code>, <code>min</code>, <code>max</code>, <code>count</code>,
        <code>avg</code>, <code>first</code>, <code>last</code>) and the
        <code>aggStage</code> / <code>filterAggStage</code> pipeline beans.
        The <code>sales</code> column here aggregates with
        <code>aggFunc: 'sum'</code>.
      </p>
      <p>
        The leading <strong>Location</strong> column is the auto group
        column — generated by <code>AutoGenColsService</code>
        (bean <code>autoColSvc</code>) and rendered by the
        <code>agGroupCellRenderer</code> user component. Its header comes
        from <code>autoGroupColumnDef: {{ '{' }} headerName: 'Location' {{ '}' }}</code>;
        click the chevron (or press <kbd>&#8629;</kbd>) to expand or collapse
        a group.
      </p>
    </div>
  `,
})
export class RowGroupingDemo {
  protected readonly theme = inject(LibreGridThemeService);
  protected readonly rowData = makeRows(50);

  protected readonly columnDefs: ColDef<Row>[] = [
    { field: 'country', rowGroup: true },
    { field: 'city', rowGroup: true },
    { field: 'product' },
    { field: 'sales', aggFunc: 'sum' },
  ];

  protected readonly gridOptions: GridOptions<Row> = {
    defaultColDef: { flex: 1 },
    groupDefaultExpanded: 1,
    autoGroupColumnDef: { headerName: 'Location', minWidth: 220 },
  };
}
